package JiraScripts.itsd.changeUnified

class Constants {
    public static final String NORMAL_CHANGE = "Normal Change"
    public static final String STANDARD_CHANGE = "Standard Pre-Approved Change"
    public static final String EXCEPTION_CHANGE = "Exception Change"
    public static final String EMERGENCY_CHANGE = "Emergency Change"
    public static final String ALL_CHANGES = "All"

    public static enum FieldSetting {OPTIONAL, MANDATORY, HIDDEN, READONLY}

    public static List<Tuple2<String, Map<String, FieldSetting>>> fields = [
            new Tuple2("CI-Services", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("CI-Component", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("CI-Class", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("CI-Type", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("CI-Change Activity", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            // new Tuple2("CI-Change Activity", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("CI-Standard-Change", [(STANDARD_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("CI-CAB-Board", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Already implemented?", [(EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("System", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            new Tuple2("Other Systems that can be affected", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Affected countries", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Change Category", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("Change reason", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Exception justification", [(EXCEPTION_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Summary", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Description", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Attachment", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("Implementation Start", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Implementation End", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Backup Solution", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Implementation plan", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Is downtime required?", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Validation plan", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Fallback plan", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Tests from lower environment", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Tests comment", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Link to the test ticket", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Was Fallback Plan tested?", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Time needed for Fallback", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Is downtime required for fallback?", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Users affected", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Type of users", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Known scenario", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Financial transactions", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Data Security Officer Approval needed", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Cyber Security Architect Approval needed", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Number of resources needed for implementation", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Time needed for implementation", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Change Requester", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Change Implementer", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("Peer Reviewer", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Change Authorities", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("IT Change Manager", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY]),
            new Tuple2("Manager on duty", [(ALL_CHANGES) : FieldSetting.READONLY]),
            new Tuple2("Related Issues", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (STANDARD_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Parent change", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (STANDARD_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Child change", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (STANDARD_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Parallel change", [(NORMAL_CHANGE) : FieldSetting.OPTIONAL, (EXCEPTION_CHANGE) : FieldSetting.OPTIONAL, (STANDARD_CHANGE) : FieldSetting.OPTIONAL]),
            // new Tuple2("Change Process Manager", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Change Process Manager", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            new Tuple2("Implementation In Maintenance Window", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            new Tuple2("Change subtype", [(NORMAL_CHANGE) : FieldSetting.READONLY, (EXCEPTION_CHANGE) : FieldSetting.READONLY, (EMERGENCY_CHANGE) : FieldSetting.READONLY, (STANDARD_CHANGE) : FieldSetting.HIDDEN]),
            new Tuple2("Change Impact", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            //new Tuple2("Change Probability", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            new Tuple2("Resolver Group", [(NORMAL_CHANGE) : FieldSetting.MANDATORY, (EXCEPTION_CHANGE) : FieldSetting.MANDATORY, (EMERGENCY_CHANGE) : FieldSetting.MANDATORY, (STANDARD_CHANGE) : FieldSetting.READONLY]),
            new Tuple2("Link to the incident ticket", [(EMERGENCY_CHANGE) : FieldSetting.OPTIONAL]),
            new Tuple2("Additional Resolver Groups", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("Submit directly to CAB", [(ALL_CHANGES) : FieldSetting.MANDATORY]),
            new Tuple2("Probability of failure", [(ALL_CHANGES) : FieldSetting.HIDDEN]),
            new Tuple2("Change risk", [(ALL_CHANGES) : FieldSetting.READONLY]),
            new Tuple2("Validation Status", [(ALL_CHANGES) : FieldSetting.OPTIONAL]),
            new Tuple2("Change Impact", [(ALL_CHANGES) : FieldSetting.READONLY]),
            new Tuple2("Change effort", [(ALL_CHANGES) : FieldSetting.HIDDEN])
    ]

    /** Map with the fields that are filled out with values from Change Activity with the name of a custom field as key and the name of the corresponding Insight attribute as value */
    public static Map<String, List<String>> CHANGE_ACTIVITY_FIELDS = [
            "Change subtype": ["Change subtype"],
            "Change Impact": ["Change Impact"],
            "Other Systems that can be affected": ["Other Systems that can be affected"],
            "Affected countries": ["Affected countries"],
            "Change reason": ["Change reason"],
            "Description": ["Description"],
            "Summary": ["Summary"],
            "Requester's Company name": ["Requester's Company name"],
            "Users affected": ["Users affected"],
            "Type of users": ["Type of users"],
            "Financial transactions": ["Financial transactions"],
            "Known scenario": ["Known scenario"],
            "Data Security Officer Approval needed": ["Data Security Officer Approval needed"],
            "Cyber Security Architect Approval needed": ["Cyber Security Architect Approval needed"],
            "Number of resources needed for implementation": ["Number of resources needed for implementation"],
            "Time needed for implementation": ["Time needed for implementation"],
            "Change Impact": ["Change Impact"],
            "Tests from lower environment": ["Tests from lower environment"],
            "Tests comment": ["Tests comment"],
            "Was Fallback Plan tested?": ["Was Fallback Plan tested"],
            "Backup Solution": ["Backup Solution"],
            "Implementation plan": ["Implementation plan"],
            "Validation plan": ["Validation plan"],
            "Fallback plan": ["Fallback plan"],
            "Is downtime required for fallback?": ["Is downtime required for fallback"],
            "Is downtime required?": ["Is downtime required"],
            "Peer Reviewer": ["Peer Reviewers"],
            "IT Change Manager": ["IT Change Managers"],
            "CI-CAB-Board": ["CAB-Board"],
            "Country": ["Country"],
            "Time needed for Fallback": ["Time needed for Fallback - hours", "Time needed for Fallback - minutes"]
    ]
}

